alter table order_product drop foreign key FKhnfgqyjx3i80qoymrssls3kno;
alter table order_product drop foreign key FKl5mnj9n0di7k1v90yxnthkc73;
alter table orders drop foreign key FK624gtjin3po807j3vix093tlf;
drop table if exists customer;
drop table if exists order_product;
drop table if exists orders;
drop table if exists product;
alter table order_product drop foreign key FKhnfgqyjx3i80qoymrssls3kno;
alter table order_product drop foreign key FKl5mnj9n0di7k1v90yxnthkc73;
alter table orders drop foreign key FK624gtjin3po807j3vix093tlf;
drop table if exists customer;
drop table if exists order_product;
drop table if exists orders;
drop table if exists product;
alter table order_product drop foreign key FKhnfgqyjx3i80qoymrssls3kno;
alter table order_product drop foreign key FKl5mnj9n0di7k1v90yxnthkc73;
alter table orders drop foreign key FK624gtjin3po807j3vix093tlf;
drop table if exists customer;
drop table if exists order_product;
drop table if exists orders;
drop table if exists product;
alter table order_product drop foreign key FKhnfgqyjx3i80qoymrssls3kno;
alter table order_product drop foreign key FKl5mnj9n0di7k1v90yxnthkc73;
alter table orders drop foreign key FK624gtjin3po807j3vix093tlf;
drop table if exists customer;
drop table if exists order_product;
drop table if exists orders;
drop table if exists product;
